"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let Br=2463534242,BE=()=>{let x=Br;x^=x<<13;x^=x>>>17;x^=x<<5;Br=x;return x;},BJ=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=Z(H(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=J(args[i]);}BT(()=>{f.call(null,
javaArgs);},callback);},B7=target=>target.$clinit=()=>{},B2=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=H();}return function(){superclass.call(this);};},Bg=cls=>BI(cls),H
=()=>D,B4=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},Bu=(name,binaryName)=>{let cls=B4();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},Bh=Bu("char","C"),Cb=Bu("int","I");
if(typeof BigInt!=='function'){}else if(typeof BigInt64Array!=='function'){}else {}function Cp(lo,hi){this.lo=lo|0;this.hi=hi|0;}
if(typeof BigInt!=="function"){}else {}if(typeof BigInt!=='function'){function Cs(lo,hi,sup){this.lo=lo;this.hi=hi;this.sup=sup;}
}else {}let Z=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (R(cls))(data);};
if(typeof BigInt64Array!=='function'){}else {}let M=sz=>new B0(new Uint16Array(sz)),R=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(H()).call(this);this.data=data;}JavaArray.prototype=Object.create((H()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.o=function(){let dataCopy;if
('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (R(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[H()],primitive:false,superclass:H(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},W,BQ
=strings=>{Ck();W=new Array(strings.length);for(let i=0;i<strings.length;++i){W[i]=Bl(J(strings[i]));}},Bb=index=>W[index],Bk=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},J=str=>str===null?null:Ce(str),Bx=str=>str===null?null:str.g,Ck=()=>(()=>{})(),Bl;
{Bl=str=>str;}let Q=ex=>{throw Cl(ex);},O=Symbol("javaException"),Cl=ex=>{let err=ex.$jsException;if(!err){let javaCause=Cg(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;err=new F("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[O]=ex;ex.$jsException=err;Ci(err,ex);}return err;},Ci=(err,ex)=>{if(typeof B$==="function"&&err.stack){let stack=B$(err.stack);let javaStack=Z(BK(),
stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=BV(J(element.className),J(element.methodName),J(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){B_(ex,javaStack);}}},F;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");F=function F(message,cause){let self=Reflect.construct(Error,[void 0,cause],F);Object.setPrototypeOf(self,F.prototype);self[defaultMessage]=message;return self;}
;F.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:F},message:{get(){try {let javaException=this[O];if(typeof javaException==='object'){let javaMessage=Bz(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {F=Error;}let BP=e=>e instanceof Error&&typeof e[O]==='object'?e[O]:null,Bz=t=>Cc(t),Cg
=t=>Cj(t),BK=()=>H(),BV=(className,methodName,fileName,lineNumber)=>{{return null;}},B_=(e,stack)=>{},Bw=null,BB=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}Bw=packages;},Cf=data=>{let packages=Bw;let i=0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex
=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo
===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func
=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}},BT=(runner,callback)=>{let result;try {result=runner();}catch(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function D(){this.$id$=0;}
let B5=a=>{let b,c,d,e,f,g,h,i,j,k,l,m;b=a;if(!b.$id$)b.$id$=BE();c=a.$id$;if(!c)d=Bb(0);else{if(!c)e=32;else{f=0;e=c>>>16|0;if(e)f=16;else e=c;g=e>>>8|0;if(!g)g=e;else f=f|8;e=g>>>4|0;if(!e)e=g;else f=f|4;g=e>>>2|0;if(!g)g=e;else f=f|2;if(g>>>1|0)f=f|1;e=(32-f|0)-1|0;}h=(((32-e|0)+4|0)-1|0)/4|0;i=M(h);j=i.data;h=(h-1|0)*4|0;e=0;while(h>=0){f=e+1|0;g=(c>>>h|0)&15;j[e]=g>=0&&g<16?(g<10?(48+g|0)&65535:((97+g|0)-10|0)&65535):0;h=h-4|0;e=f;}d=B6(i);}b=new Be;b.h=M(16);Bq(Bq(b,Bb(1)),d);k=new G;i=b.h;j=i.data;l=
b.i;m=j.length;if(l>=0&&l<=(m-0|0)){k.g=Bk(i.data,0,l);return k;}Q(BU());},Bn=E(),U=()=>{U=B7(Bn);BX();},BC=b=>{let c,d,e;U();c=window.document;d=c.createElement("div");e=c.createTextNode("TeaVM generated element");d.appendChild(e);c.body.appendChild(d);},BX=()=>{BM();BD();Cd();},Bd=E(0),Bt=E(0);
function Bs(){D.call(this);this.n=null;}
let BI=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new Bs;c.n=b;b.classObject=c;}return c;},Cn=E(),B3=E();
function T(){let a=this;D.call(a);a.l=null;a.m=null;a.k=0;a.j=0;}
let Cr=a=>{return a;},Cc=a=>{return a.l;},Cj=a=>{let b;b=a.m;if(b===a)b=null;return b;},Ba=E(T),I=E(Ba),BY=(a,b)=>{a.k=1;a.j=1;a.l=b;},Cq=a=>{let b=new I();BY(b,a);return b;},Ch=E(I),K=E(0),L=E(0),P=E(0),G=E(),BN=null,B1=null,BF=null,BL=(a,b)=>{a.g=Bk(b.data,0,b.data.length);},B6=a=>{let b=new G();BL(b,a);return b;},BA=(a,b)=>{a.g=b;},Ce=a=>{let b=new G();BA(b,a);return b;},BM=()=>{let b;BN=M(0);b=new G;b.g="";B1=b;BF=new Bf;},X=E(),BO=E(X),BS=null,BD=()=>{BS=Bg(Cb);};
function V(){let a=this;D.call(a);a.h=null;a.i=0;}
let BZ=(a,b)=>{let c,d,e,f,g;c=a.h.data.length;if(c>=b)return;d=c>=1073741823?2147483647:Bi(b,Bi(c*2|0,5));e=a.h.data;f=M(d);b=e.length;if(d<b)b=d;g=f.data;c=0;while(c<b){g[c]=e[c];c=c+1|0;}a.h=f;},By=E(0),Be=E(V),Bq=(a,b)=>{let c,d,e,f,g;c=a.i;if(b===null)b=Bb(2);if(c>=0&&c<=c){d=b.g.length?0:1;a:{if(!d){BZ(a,a.i+b.g.length|0);e=a.i-1|0;while(e>=c){a.h.data[e+b.g.length|0]=a.h.data[e];e=e+(-1)|0;}a.i=a.i+b.g.length|0;d=0;while(d<b.g.length){f=a.h;g=c+1|0;if(d<0)break a;if(d>=b.g.length)break a;f.data[c]=b.g.charCodeAt(d);d
=d+1|0;c=g;}}return a;}Q(BW());}b=new Y;Bc(b);Q(b);},S=E(0),Bj=E(0),Bm=E(0),Bp=E(0),BG=E(),Ca=E(),Bo=E(0),Bf=E(),Bv=E(),BR=null,B8=null,Cd=()=>{BR=Bg(Bh);B8=Z(Bv,128);},BH=E(),N=E(I),Bc=a=>{a.k=1;a.j=1;},BU=()=>{let a=new N();Bc(a);return a;},Y=E(N),Co=a=>{Bc(a);},BW=()=>{let a=new Y();Co(a);return a;},B9=E(),Bi=(b,c)=>{if(b>c)c=b;return c;},Cm=E();
BB([]);
Cf([D,0,0,[],0,3,0,0,0,Bn,0,D,[],0,3,0,U,0,Bd,0,D,[],3,3,0,0,0,Bt,0,D,[],3,3,0,0,0,Bs,0,D,[Bd,Bt],0,3,0,0,0,Cn,0,D,[],4,0,0,0,0,B3,0,D,[],4,3,0,0,0,T,0,D,[],0,3,0,0,0,Ba,0,T,[],0,3,0,0,0,I,0,Ba,[],0,3,0,0,0,Ch,0,I,[],0,3,0,0,0,K,0,D,[],3,3,0,0,0,L,0,D,[],3,3,0,0,0,P,0,D,[],3,3,0,0,0,G,0,D,[K,L,P],0,3,0,0,0,X,0,D,[K],1,3,0,0,0,BO,0,X,[L],0,3,0,0,0,V,0,D,[K,P],0,0,0,0,0,By,0,D,[],3,3,0,0,0,Be,0,V,[By],0,3,0,0,0,S,0,D,[],3,3,0,0,0,Bj,0,D,[S],3,3,0,0,0,Bm,0,D,[Bj],3,3,0,0,0,Bp,0,D,[S],3,3,0,0,0,BG,0,D,[Bm,Bp],1,
3,0,0,0,Ca,0,D,[],4,3,0,0,0,Bo,0,D,[],3,3,0,0,0,Bf,0,D,[Bo],0,3,0,0,0,Bv,0,D,[L],0,3,0,0,0,BH,0,D,[],4,3,0,0,0,N,0,I,[],0,3,0,0,0,Y,0,N,[],0,3,0,0,0,B9,0,D,[],4,3,0,0,0,Cm,0,D,[],0,3,0,0,0]);
let B0=R(Bh);
BQ(["0","<java_object>@","null"]);
G.prototype.toString=function(){return Bx(this);};
G.prototype.valueOf=G.prototype.toString;D.prototype.toString=function(){return Bx(B5(this));};
D.prototype.__teavm_class__=function(){return B2(this);};
let C=BJ(BC);
C.javaException=BP;
B.main=C;}));

//# sourceMappingURL=classes.js.map